name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json

      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ steps.release.outputs.releases_created }} == 'true'

      - uses: pnpm/action-setup@v2
        if: ${{ steps.release.outputs.releases_created }} == 'true'
        with:
          version: 9.15.2

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        if: ${{ steps.release.outputs.releases_created }} == 'true'
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org'
          scope: '@pdtp'

      - name: install dependencies
        if: ${{ steps.release.outputs.releases_created }} == 'true'
        run: pnpm install

      - name: build
        if: ${{ steps.release.outputs.releases_created }} == 'true'
        run: pnpm -r build

      - name: lint
        if: ${{ steps.release.outputs.releases_created }} == 'true'
        run: pnpm -r lint

      - name: publish
        if: ${{ steps.release.outputs.releases_created }} == 'true'
        run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}